name: cognite_cdf_sdk
description: >-
  Read-only SDK for Cognite Data Fusion (CDF) (https://docs.cognite.com/dev/).
  This SDK is a community project.
homepage: https://github.com/gregertw/cognite-sdk-dart
version: 0.1.2-dev.3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dio: ^3.0.10
  logger: ^0.9.4
  mockito: ^4.1.3 

dev_dependencies:
  flutter_test:
    sdk: flutter