name: cognite_cdf_sdk
description: >-
  Read-only SDK for Cognite Data Fusion (CDF) (https://docs.cognite.com/dev/).
  This SDK is a community project.
homepage: https://github.com/gregertw/cognite-sdk-dart
version: 0.2.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  logger: ^1.0.0
  mockito: ^5.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter